<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>手机贪吃蛇</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            background-color: #2c3e50;
            touch-action: none;
        }
        #gameCanvas {
            border: 2px solid #ecf0f1;
            margin-top: 20px;
        }
        #controls {
            margin-top: 20px;
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 10px;
        }
        .control-btn {
            padding: 15px;
            font-size: 24px;
            background-color: #3498db;
            border: none;
            border-radius: 5px;
            color: white;
            touch-action: none;
        }
    </style>
</head>
<body>
    <div id="score">得分: 0</div>
    <canvas id="gameCanvas"></canvas>
    <div id="controls">
        <div></div>
        <button class="control-btn" id="upBtn">↑</button>
        <div></div>
        <button class="control-btn" id="leftBtn">←</button>
        <button class="control-btn" id="downBtn">↓</button>
        <button class="control-btn" id="rightBtn">→</button>
    </div>

<script>
    const canvas = document.getElementById('gameCanvas');
    const ctx = canvas.getContext('2d');
    const scoreElement = document.getElementById('score');
    
    // 设置画布大小
    const setCanvasSize = () => {
        canvas.width = Math.min(window.innerWidth - 20, 400);
        canvas.height = canvas.width;
    }
    setCanvasSize();
    window.addEventListener('resize', setCanvasSize);

    const gridSize = 20;
    let snake = [{x: 10, y: 10}];
    let food = {x: 15, y: 15};
    let dx = 0;
    let dy = 0;
    let score = 0;
    let gameLoop;

    function drawGame() {
        // 移动蛇
        const head = {x: snake[0].x + dx, y: snake[0].y + dy};
        snake.unshift(head);

        // 检查是否吃到食物
        if (head.x === food.x && head.y === food.y) {
            score += 10;
            scoreElement.textContent = `得分: ${score}`;
            generateFood();
        } else {
            snake.pop();
        }

        // 清除画布
        ctx.fillStyle = '#2c3e50';
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        // 绘制蛇
        ctx.fillStyle = '#2ecc71';
        snake.forEach(segment => {
            ctx.fillRect(segment.x * gridSize, segment.y * gridSize, 
                        gridSize - 2, gridSize - 2);
        });

        // 绘制食物
        ctx.fillStyle = '#e74c3c';
        ctx.fillRect(food.x * gridSize, food.y * gridSize, 
                    gridSize - 2, gridSize - 2);

        // 碰撞检测
        if (checkCollision()) {
            gameOver();
        }
    }

    function generateFood() {
        food.x = Math.floor(Math.random() * (canvas.width / gridSize));
        food.y = Math.floor(Math.random() * (canvas.height / gridSize));
    }

    function checkCollision() {
        const head = snake[0];
        return (
            head.x < 0 || head.x >= canvas.width / gridSize ||
            head.y < 0 || head.y >= canvas.height / gridSize ||
            snake.slice(1).some(segment => segment.x === head.x && segment.y === head.y)
        );
    }

    function gameOver() {
        clearInterval(gameLoop);
        alert(`游戏结束！得分: ${score}`);
        resetGame();
    }

    function resetGame() {
        snake = [{x: 10, y: 10}];
        dx = 0;
        dy = 0;
        score = 0;
        scoreElement.textContent = '得分: 0';
        generateFood();
        gameLoop = setInterval(drawGame, 200);
    }

    // 触摸控制
    document.getElementById('upBtn').addEventListener('touchstart', () => {
        if (dy !== 1) { dx = 0; dy = -1; }
    });
    document.getElementById('downBtn').addEventListener('touchstart', () => {
        if (dy !== -1) { dx = 0; dy = 1; }
    });
    document.getElementById('leftBtn').addEventListener('touchstart', () => {
        if (dx !== 1) { dx = -1; dy = 0; }
    });
    document.getElementById('rightBtn').addEventListener('touchstart', () => {
        if (dx !== -1) { dx = 1; dy = 0; }
    });

    // 启动游戏
    generateFood();
    gameLoop = setInterval(drawGame, 200);
</script>
</body>
</html>
